name: Update Simulation from Issue Input

on:
  issues:
    types: [ opened, edited ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'just for fun')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: install module
        run: pip install -e .

      - name: Get Issue Content
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo $ISSUE_BODY > issue_body.txt

      - name: Get onto main
        run: |
          git fetch
          git checkout main
          git pull

      - name: Update asset
        run: python .github/scripts/make_asset.py

      - name: Configure Git and Push asset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/simulation.png
          git commit -m "Auto-create simulation for README from user issue input" || exit 0
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Close issue
        run: |
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -d '{"state": "closed"}' \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
